##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    - autoconf-archive
    - caja
    - clang
    - dblatex
    - gcc
    - git
    - libxml2
    - libgtop2
    - libICE
    - libSM
    - libuuid
    - make
    - mate-common
    - yelp-tools

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/caja-actions
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - dblatex
    - docbook-utils
    - gcc
    - git
    - libcaja-extension-dev
    - libgtk-3-dev
    - libgtop2-dev
    - libsm-dev
    - libxml2-dev
    - make
    - mate-common
    - uuid-dev
    - yelp-tools

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/caja-actions.git
    - autoconf-archive
    - caja-devel
    - clang
    - clang-analyzer
    - dblatex
    - gcc
    - git
    - libxml2-devel
    - libgtop2-devel
    - libICE-devel
    - libSM-devel
    - libuuid-devel
    - make
    - mate-common
    - gtk3-devel
    - yelp-tools

  ubuntu:
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - dblatex
    - docbook-utils
    - gcc
    - git
    - libcaja-extension-dev
    - libgtk-3-dev
    - libgtop2-dev
    - libsm-dev
    - libxml2-dev
    - make
    - mate-common
    - uuid-dev
    - yelp-tools

variables:
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

before_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     egrep -lRZ 'G_GNUC_BEGIN_IGNORE_DEPRECATIONS' . | xargs -0 -l sed -i -e 's/G_GNUC_BEGIN_IGNORE_DEPRECATIONS/ /g'
  -     egrep -lRZ 'G_GNUC_END_IGNORE_DEPRECATIONS' . | xargs -0 -l sed -i -e 's/G_GNUC_END_IGNORE_DEPRECATIONS/ /g'
  - fi

build_scripts:
  - NOCONFIGURE=1 ./autogen.sh
  - scan-build $CHECKERS ./configure  --enable-deprecated --enable-html-manuals --enable-pdf-manuals
  - if [ $CPU_COUNT -gt 1 ]; then
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  - else
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude --force -D__cplusplus .
  - fi

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: caja-actions-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
