#! /bin/sh

PACKAGE=caja-actions;
PACKAGE_HELP=caja-actions-config-tool;

# normal translations
make -C po $PACKAGE.pot && mv po/$PACKAGE.pot .
sed -i "/#, fuzzy/d" $PACKAGE.pot

# translations for user-quide
rm -f docs/help/$PACKAGE_HELP.pot &&
make -C docs/help $PACKAGE_HELP.pot &&
mv docs/help/$PACKAGE_HELP.pot .
